### ISSUE TITLE
Testing the issues tool

### ISSUE THREAD

**Issue by vicente-gonzalez-ruiz** [Sistemas-Multimedia/live-streaming#1]
Hi every body!

Best regards,
Vicente.

PD: Si no es un inconveniente, prefiero que escribáis en inglés porque esto ayuda a que los proyectos públicos, como éste, lleguen a más personas. Pero vamos, que no es un requerimiento imprescindible :-)

**Comment by cnelmortimer** [comment]
Received and read!

**Comment by robertosalas** [comment]
Perfect!
Ready to start!

**Comment by RocioSM** [comment]
Ok, received the email.


2015-04-18 13:10 GMT+02:00 Roberto Salas <notifications@github.com>:
